# Generated by Django 5.1.2 on 2024-10-30 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=100)),
                ('dados_pessoais', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidates.dadospessoais')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('entrada', models.DateField()),
                ('saida', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.dadospessoais')),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('fim', models.DateField(blank=True, null=True)),
                ('dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.dadospessoais')),
            ],
        ),
    ]
